-- Insertar categorías (asumiendo que la tabla tiene "id" autoincremental)
INSERT INTO CATEGORIA (nombre) VALUES
('Solares'),
('HigieneDental'),
('Corporales'),
('CuidadosFaciales');

-- Insertar productos (CATEGORIA_ID debe ser 1, 2, 3 o 4)
INSERT INTO PRODUCTO (NOMBRE, DESCRIPCION, IMAGEN_URL, PRECIO, CATEGORIA_ID, MAS_VENDIDO) VALUES
('autobronceado', 'autobronceado', 'https://tienda.pilar-delgado.com/4704-large_default/institut-esthederm-reflets-de-soleil-autobronceador-gel-crema.jpg', 17.99, 1, FALSE),
('avene-solar-cleanance-anti-imperfecciones-spf-50-50-ml', 'avene-solar-cleanance-anti-imperfecciones-spf-50-50-ml', 'https://www.druni.es/media/catalog/product/5/0/5013169.jpg', 14.95, 1, TRUE),
('bioderma-photoderm-crema-con-color-light-spf50-40-ml', 'bioderma-photoderm-crema-con-color-light-spf50-40-ml', 'https://www.dermofarma.es/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/h/photoderm_m_gel-crema_spf_50_color_marr_n_40_ml._-_bioderma.png', 18.95, 1, FALSE),
('eucerin-sun-gel-crema-oil-control-dry-touch-fps50-50-ml', 'eucerin-sun-gel-crema-oil-control-dry-touch-fps50-50-ml', 'https://images-1.eucerin.com/~/media/eucerin%20relaunch%20media/eucerin/local/es/products/sun-protection/sun%20gel%20crema%20oil%20control%20dry%20touch%20fps50/2023/1.jpg?rx=0&ry=0&rw=2000&rh=2000&hash=75C4A02A83635C6B526CB46ECA87672F', 9.95, 1, FALSE),
('klorane-crema-depilat-150-ml', 'klorane-crema-depilat-150-ml', 'https://www.farmavazquez.com/44866/581504.jpg', 13.95, 1, FALSE),
('la-roche-posay-anthelios-fluido-invisible-sin-perfume-spf50-50-ml', 'la-roche-posay-anthelios-fluido-invisible-sin-perfume-spf50-50-ml', 'https://farmaciajimenez.com/storage/products/la-roche-posay-anthelios-shaka-fluid-spf50-50-ml/la-roche-posay-anthelios-uv-mune-400-spf50-fluido-invisible-50-ml-1-1440.jpg', 13.95, 1, FALSE),
('vichy-capital-soleil-leche-solar-hidratante-spf50-300-ml', 'vichy-capital-soleil-leche-solar-hidratante-spf50-300-ml', 'https://www.farmaciabarata.es/39554/vichy-capital-soleil-leche-hidratante-spf50.jpg', 13.99, 1, FALSE),
('cepillo-dental-infantil-kin', 'cepillo-dental-infantil-kin', 'https://www.farmavazquez.com/113745-large_default/cepillo-dental-infantil-kin.jpg', 6.95, 2, FALSE),
('cepillo-interprox-plus-conic', 'cepillo-interprox-plus-conic', 'https://farmaciasenante.com/19069-thickbox_default/cepillo-interprox-plus-conic.jpg', 5.95, 2, FALSE),
('fluocaril-interdental-pro-kit-inicial-medio', 'fluocaril-interdental-pro-kit-inicial-medio', 'https://www.farmavazquez.com/92286-large_default/fluocaril-interdental-pro-kit-inicial-medio.jpg', 9.95, 2, FALSE),
('oral-b-cepillo-electrico-io-2-blanco', 'oral-b-cepillo-electrico-io-2-blanco', 'https://farmaciacampolivar.es/15884-large_default/oral-b-cepillo-electrico-io-2-blanco.jpg', 46.95, 2, FALSE),
('oraldine-clasico', 'oraldine-clasico', 'https://www.pharmashop.es/32643-thickbox_default/oraldine-colutorio-antiseptico-pack-400-ml-200-ml.jpg', 18.99, 2, TRUE),
('phb-plus-cepillo-medio-duplo', 'phb-plus-cepillo-medio-duplo', 'https://www.farmavazquez.com/38074-thickbox_default/phb-plus-cepillo-medio-duplo.jpg', 4.95, 2, FALSE),
('tepe-cepillo-dental-adulto-supreme-suave', 'tepe-cepillo-dental-adulto-supreme-suave', 'https://www.farmavazquez.com/36130-large_default/tepe-cepillo-dental-adulto-supreme-suave.jpg', 12.95, 2, FALSE),
('vitis-anticaries-colutorio-bucal-500-ml', 'vitis-anticaries-colutorio-bucal-500-ml', 'https://media.farmacianuriapau.com/product/vitis-anticaries-colutorio-bucal-500-ml-800x800.jpg', 6.95, 2, FALSE),
('drtree-gel-de-ducha-solido-exfoliante-cosmos-120-g', 'drtree-gel-de-ducha-solido-exfoliante-cosmos-120-g', 'https://www.farmavazquez.com/81202-medium_default/drtree-gel-de-ducha-solido-exfoliante-cosmos-120-g.jpg', 6.95, 3, FALSE),
('eucerin-pack-ahorro-ph5-locion-enriquecida-1-l-gel-bano-200-ml', 'eucerin-pack-ahorro-ph5-locion-enriquecida-1-l-gel-bano-200-ml', 'https://www.farmavazquez.com/113257-large_default/eucerin-pack-ahorro-ph5-locion-enriquecida-1-l-gel-bano-200-ml.jpg', 20.99, 3, TRUE),
('eucerin-ph5-oleogel-ducha-1000-ml', 'eucerin-ph5-oleogel-ducha-1000-ml', 'https://productimages.etrusted.com/products/prt-c6210bf5-8646-40b8-98ae-13da902d0af7/3/original.jpg', 8.95, 3, FALSE),
('germisdin-aloe-vera-piel-seca-1000-ml', 'germisdin-aloe-vera-piel-seca-1000-ml', 'https://farmaciasenante.com/37779-large_default/germisdin-piel-seca-1000-ml.jpg', 11.95, 3, FALSE),
('isdin-lambda-control-roll-on-duplo-50-ml', 'isdin-lambda-control-roll-on-duplo-50-ml', 'https://farmaciaolmos.es/78933-large_default/lambda-control-roll-on-50ml-duplo.jpg', 8.95, 3, FALSE),
('uriage-duplo-desodorante-fresh-spray-2-x-125-ml', 'uriage-duplo-desodorante-fresh-spray-2-x-125-ml', 'https://www.farmavazquez.com/122623-large_default/uriage-duplo-desodorante-fresh-spray-2-x-125-ml.jpg', 6.95, 3, FALSE),
('mi-rebotica-gel-de-bao-proteinas-de-leche-250-ml', 'mi-rebotica-gel-de-bao-proteinas-de-leche-250-ml', 'https://www.farmavazquez.com/89875-large_default/mi-rebotica-gel-de-bao-proteinas-de-leche-250-ml.jpg', 5.95, 1, FALSE),
('uriage-promo-xemose-balsamo-500-ml-aceite-limpiador-200-ml', 'uriage-promo-xemose-balsamo-500-ml-aceite-limpiador-200-ml', 'https://www.farmavazquez.com/80220-large_default/uriage-promo-xemose-balsamo-500-ml-aceite-limpiador-200-ml.jpg', 13.95, 3, FALSE),
('endocare-protocolo-reafirmante-tensage-crema-nutritiva-50-ml-tensage-10-ampollas', 'endocare-protocolo-reafirmante-tensage-crema-nutritiva-50-ml-tensage-10-ampollas', 'https://cosmeticabionatural.es/12802-large_default/endocare-protocolo-reafirmante-crema-y-ampollas-regeneradoras-y-antiarrugas-con-efecto-tensor.jpg', 21.99, 4, TRUE),
('elisa-garcia-esponja-maquillaje', 'elisa-garcia-esponja-maquillaje', 'https://www.farmavazquez.com/126997-large_default/elisa-garcia-esponja-maquillaje.jpg', 4.95, 4, FALSE),
('elisa-garcia-iluminador-liquido-rusty-20ml', 'elisa-garcia-iluminador-liquido-rusty-20ml', 'https://www.farmavazquez.com/129591-home_default/elisa-garcia-iluminador-liquido-rusty-20ml.jpg', 16.95, 4, FALSE),
('elisa-garcia-pincel-abanico-para-iluminador-n-19', 'elisa-garcia-pincel-abanico-para-iluminador-n-19', 'https://www.farmavazquez.com/126993-home_default/elisa-garcia-pincel-abanico-para-iluminador-n19.jpg', 7.95, 4, FALSE),
('elisa-garcia-polvo-iluminador-n-3-6g', 'elisa-garcia-polvo-iluminador-n-3-6g', 'https://www.farmavazquez.com/128399/638118.jpg', 10.95, 4, FALSE),
('esponja-jabonosa-acofar', 'esponja-jabonosa-acofar', 'https://www.farmavazquez.com/54010/591440.jpg', 8.95, 4, FALSE),
('eucerin-hyaluron-filler-elasticity-crema-de-dia-rose-fps30-50-ml', 'eucerin-hyaluron-filler-elasticity-crema-de-dia-rose-fps30-50-ml', 'https://statics.promofarma.com/static/promofarma/prod/product_images/z/9ADL4_es_ES_0.jpeg', 39.99, 4, FALSE),
('serum-acido-hialuronico-4d-provitamina-b5-20-ml', 'serum-acido-hialuronico-4d-provitamina-b5-20-ml', 'https://www.farmavazquez.com/122091-large_default/farmavazquez-serum-acido-hialuronico-4d-provitamina-b5-20-ml.jpg', 17.99, 4, FALSE),
('sesderma-c-vit-liposomal-serum-30-ml', 'sesderma-c-vit-liposomal-serum-30-ml', 'https://farmaciasenante.com/30137-thickbox_default/sesderma-c-vit-liposomal-serum-30ml.jpg', 24.99, 4, FALSE);